---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/chats/create":
    post:
      summary: Create chat
      tags:
      - Chats
      parameters: []
      responses:
        '201':
          description: chat created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      reference:
                        type: string
                      token:
                        type: string
                      active:
                        type: boolean
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chat:
                  type: object
                  properties:
                    reference:
                      type: string
                      example: REF-123
                  required:
                  - reference
  "/v1/chats/list":
    get:
      summary: List chats
      tags:
      - Chats
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      responses:
        '200':
          description: chats found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        reference:
                          type: string
                        token:
                          type: string
                        active:
                          type: boolean
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  paginate:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                      next_page:
                        type:
                        - integer
                        - 'null'
                      prev_page:
                        type:
                        - integer
                        - 'null'
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
